# Generated by Django 2.2.7 on 2019-11-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('UN', 'Unknown'), ('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('CH', "Children's"), ('CO', 'Comedy'), ('CR', 'Crime'), ('DO', 'Documental'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('FI', 'Film-Noir'), ('HO', 'Horror'), ('MU', 'Musical')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('categoria_preferida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('anyo', models.IntegerField()),
                ('resumen', models.TextField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.Categoria')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.Director')),
            ],
        ),
    ]
