# Generated by Django 2.2.7 on 2019-11-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='categoria',
            field=models.CharField(choices=[('UN', 'Unknown'), ('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('CH', "Children's"), ('CO', 'Comedy'), ('CR', 'Crime'), ('DO', 'Documental'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('FI', 'Film-Noir'), ('HO', 'Horror'), ('MU', 'Musical')], default='UN', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='categoria_preferida',
            field=models.CharField(choices=[('UN', 'Unknown'), ('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('CH', "Children's"), ('CO', 'Comedy'), ('CR', 'Crime'), ('DO', 'Documental'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('FI', 'Film-Noir'), ('HO', 'Horror'), ('MU', 'Musical')], default='UN', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
